### ISSUE TITLE
Could not run the example_basic and example_advanced

### ISSUE THREAD

**Issue by mustansarfiaz** [funkelab/linajea#56]
Hi,
We found your repo very interesting and wanted to reproduce the numbers. As a newbie in this area, I tried to run the run_basic.ipynb and run_advanced.ipynb files. However, both give errors. Here are the details.

**For run_basic.ipynb:**

raise ServerSelectionTimeoutError(pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64133448037fa0fadb53aa9a, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
2023-03-16 19:23:48,952 daisy.scheduler ERROR    pre_check() exception for block ('linajea_prediction', 12336)
Traceback (most recent call last):
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/src/daisy/daisy/scheduler.py", line 199, in __precheck
    return self.task_map[block.task_id].check_function(block)
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <lambda>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <listcomp>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 139, in <lambda>
    cf.append(lambda b: check_function(
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/daisy_check_functions.py", line 17, in check_function
    result = daisy_coll.find_one({'_id': block.block_id[1]})
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/collection.py", line 1491, in find_one
    for result in cursor.limit(-1):
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1280, in next
    if len(self.__data) or self._refresh():
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2027, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1976, in __start_session
    server_session = self._get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2013, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 525, in get_server_session
    session_timeout = self._check_session_support()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 507, in _check_session_support
    self._select_servers_loop(
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64133466037fa0fadb53aa9b, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
2023-03-16 19:24:19,528 daisy.scheduler ERROR    pre_check() exception for block ('linajea_prediction', 14360)
Traceback (most recent call last):
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/src/daisy/daisy/scheduler.py", line 199, in __precheck
    return self.task_map[block.task_id].check_function(block)
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <lambda>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <listcomp>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 139, in <lambda>
    cf.append(lambda b: check_function(
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/daisy_check_functions.py", line 17, in check_function
    result = daisy_coll.find_one({'_id': block.block_id[1]})
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/collection.py", line 1491, in find_one
    for result in cursor.limit(-1):
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1280, in next
    if len(self.__data) or self._refresh():
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2027, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1976, in __start_session
    server_session = self._get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2013, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 525, in get_server_session
    session_timeout = self._check_session_support()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 507, in _check_session_support
    self._select_servers_loop(
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64133485037fa0fadb53aa9c, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
2023-03-16 19:24:50,114 daisy.scheduler ERROR    pre_check() exception for block ('linajea_prediction', 16660)
Traceback (most recent call last):
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/src/daisy/daisy/scheduler.py", line 199, in __precheck
    return self.task_map[block.task_id].check_function(block)
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <lambda>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 153, in <listcomp>
    else lambda b: all([f(b) for f in cf])),
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 139, in <lambda>
    cf.append(lambda b: check_function(
  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/daisy_check_functions.py", line 17, in check_function
    result = daisy_coll.find_one({'_id': block.block_id[1]})
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/collection.py", line 1491, in find_one
    for result in cursor.limit(-1):
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1280, in next
    if len(self.__data) or self._refresh():
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2027, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1976, in __start_session
    server_session = self._get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2013, in _get_server_session
    return self._topology.get_server_session()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 525, in get_server_session
    session_timeout = self._check_session_support()
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 507, in _check_session_support
    self._select_servers_loop(
  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 641334a4037fa0fadb53aa9d, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

Execution Summary
-----------------

  Task linajea_prediction:

    num blocks : 240
    completed ✔: 0 (skipped 0)
    failed    ✗: 240
    orphaned  ∅: 0

Traceback (most recent call last):

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/run_basic.py", line 212, in <module>
    predict_blockwise(val_config)

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/process_blockwise/predict_blockwise.py", line 161, in predict_blockwise
    cand_db = CandidateDatabase(

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/linajea/utils/candidate_database.py", line 63, in __init__
    super().__init__(

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/src/daisy/daisy/persistence/mongodb_graph_provider.py", line 141, in __init__
    raise e

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/linajea-master/src/daisy/daisy/persistence/mongodb_graph_provider.py", line 103, in __init__
    if self.db_name not in self.client.list_database_names():

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2128, in list_database_names
    return [doc["name"] for doc in self.list_databases(session, nameOnly=True)]

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2110, in list_databases
    res = admin._retryable_read_command(cmd, session=session)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/database.py", line 870, in _retryable_read_command
    return self.__client._retryable_read(_cmd, read_preference, session)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1606, in _retryable_read
    server = self._select_server(read_pref, session, address=address)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1436, in _select_server
    server = topology.select_server(server_selector)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 250, in select_server
    return random.choice(self.select_servers(selector, server_selection_timeout, address))

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 211, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 641334c2037fa0fadb53aa9e, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

**Similary for run_advanced.ipynb:**

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/test/run_advanced.py", line 244, in <module>
    for inf_config in linajea.utils.getNextInferenceData(val_args):

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/test/linajea/utils/get_next_inference_data.py", line 121, in getNextInferenceData
    sample.db_name = checkOrCreateDB(

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/test/linajea/utils/check_or_create_db.py", line 52, in checkOrCreateDB
    return _checkOrCreateDBMeta(db_host, info, prefix=prefix,

  File "/data1/Medical/WIS/Cell_trackingggg/linajea/Codes/test/linajea/utils/check_or_create_db.py", line 61, in _checkOrCreateDBMeta
    for db_name in client.list_database_names():

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2128, in list_database_names
    return [doc["name"] for doc in self.list_databases(session, nameOnly=True)]

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 2110, in list_databases
    res = admin._retryable_read_command(cmd, session=session)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/database.py", line 870, in _retryable_read_command
    return self.__client._retryable_read(_cmd, read_preference, session)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1606, in _retryable_read
    server = self._select_server(read_pref, session, address=address)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1436, in _select_server
    server = topology.select_server(server_selector)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 250, in select_server
    return random.choice(self.select_servers(selector, server_selection_timeout, address))

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 211, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)

  File "/home/mbzuaiser/anaconda3/envs/auto_wis/lib/python3.8/site-packages/pymongo/topology.py", line 226, in _select_servers_loop
    raise ServerSelectionTimeoutError(

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6415d91e4be84e3b4ad1431a, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

**Comment by abred** [comment]
Hello,

it seems it cannot connect to the database server. Do you have a running mongodb server? (See database section within the notebooks)

**Comment by abred** [comment]
Please let us know if you run into any further issues.
